name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # now I will use my custom action
      - name: Load & Cache dependencies
        id: cached-deps
        # I have to specify where is it located (path)
        # if I have the custom action in another repo, then I must specify the repo name
        # <yourGithubAccountName>/<yourRepoName>
        # you do not need to specify the .yml extention, this will be detected automatically
        # the path is about the root of the repo, and not from "here"
        uses: ./.github/actions/cached-deps
        # here we specify the input to the action
        with:
          # this will disable caching for this job (we do not need this)
          caching: false
      - name: Output information
        run: echo "Cache used ${{ steps.cached-deps.outputs.used-cache }}"
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # now I will use my custom action
      - name: Load & Cache dependencies
        # I have to specify where is it located (path)
        # if I have the custom action in another repo, then I must specify the repo name
        # <yourGithubAccountName>/<yourRepoName>
        # you do not need to specify the .yml extention, this will be detected automatically
        # the path is about the root of the repo, and not from "here"
        uses: ./.github/actions/cached-deps
      - name: Lint code
        run: npm run lint
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      #
      # now I will use my custom action
      - name: Load & Cache dependencies
        # I have to specify where is it located (path)
        # if I have the custom action in another repo, then I must specify the repo name
        # <yourGithubAccountName>/<yourRepoName>
        # you do not need to specify the .yml extention, this will be detected automatically
        # the path is about the root of the repo, and not from "here"
        uses: ./.github/actions/cached-deps
      - name: Build website
        run: npm run build
        # here are the artifacts this step will produce, we will upload them to S3 !
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      # Next we will use the custom JS action we created to deploy the artifacts
      # or any other files we want to deploy to S3
      - name: Deploy site
        # we point to the path of the custom action
        uses: ./.github/actions/deploy-s3-javascript
        # we need to provide the access key and secret key of the aws bucket, in order t perform the file upload from out action -> to the bucket
        # since we need this creds only at this step level, we will add them here
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # since we need to provide inputs to the action, we will do it here
        with:
          # I need to provide my bucket name
          bucket: gha-custom-bucket
          # here I must point to the location where the downloaded artifacts are (we uploaded them in the previous step)
          dist-folder: ./dist
