name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # now I will use my custom action
      - name: Load & Cache dependencies
        # I have to specify where is it located (path)
        # if I have the custom action in another repo, then I must specify the repo name
        # <yourGithubAccountName>/<yourRepoName>
        # you do not need to specify the .yml extention, this will be detected automatically
        # the path is about the root of the repo, and not from "here"
        uses: ./.github/actions/cached-deps
        # here we specify the input to the action
        with:
          # this will disable caching for this job (we do not need this)
          caching: false
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # now I will use my custom action
      - name: Load & Cache dependencies
        # I have to specify where is it located (path)
        # if I have the custom action in another repo, then I must specify the repo name
        # <yourGithubAccountName>/<yourRepoName>
        # you do not need to specify the .yml extention, this will be detected automatically
        # the path is about the root of the repo, and not from "here"
        uses: ./.github/actions/cached-deps
      - name: Lint code
        run: npm run lint
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      #
      # now I will use my custom action
      - name: Load & Cache dependencies
        # I have to specify where is it located (path)
        # if I have the custom action in another repo, then I must specify the repo name
        # <yourGithubAccountName>/<yourRepoName>
        # you do not need to specify the .yml extention, this will be detected automatically
        # the path is about the root of the repo, and not from "here"
        uses: ./.github/actions/cached-deps
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."
